<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <!-- Helpers every test project shares. -->
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)Shared/*.cs" Link="Shared/%(Filename)%(Extension)" />
    <Using Include="Claudette.Tests" />
  </ItemGroup>
</Project>
